---
abstract: 'Dist::Zilla Plugin for Inline::Module'
author:
  - 'Ingy döt Net <ingy@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.021, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-Plugin-InlineModule
no_index:
  directory:
    - inc
    - t
    - xt
    - example
requires:
  Dist::Zilla: '5.019'
  Dist::Zilla::Plugin::MakeMaker::Awesome: '0'
  perl: v5.8.1
resources:
  bugtracker: https://github.com/ingydotnet/dist-zilla-plugin-inlinemodule-pm/issues
  homepage: https://github.com/ingydotnet/dist-zilla-plugin-inlinemodule-pm
  repository: https://github.com/ingydotnet/dist-zilla-plugin-inlinemodule-pm.git
version: '0.01'
